services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_volume:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: root
      DB_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html


volumes:
  db_volume: